spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/brutally_honest_mirror
spring.datasource.username=shubhaban
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
